-- WARAWAVE - ACTUALIZACIÓN DE BASE DE DATOS


-- 1) PERFILES Y AUTENTICACIÓN SEGURA (SUPABASE AUTH)
alter table public.usuarios
    add column if not exists auth_id uuid unique references auth.users(id) on delete cascade,
    add column if not exists rol text not null default 'ciudadano',
    add column if not exists activo boolean not null default true,
    add column if not exists fecha_creacion timestamptz not null default now();


alter table public.usuarios alter column password drop not null;

alter table public.usuarios
    drop constraint if exists usuarios_rol_valido;
alter table public.usuarios
    drop constraint if exists rol_valido;
alter table public.usuarios
    add constraint usuarios_rol_valido
    check (rol in ('ciudadano', 'administrador', 'autoridad'));

create unique index if not exists usuarios_correo_unico
    on public.usuarios (lower(correo));

-- Crea o enlaza automáticamente el perfil cuando alguien se registra
-- mediante Supabase Auth. Si el correo ya existía en la tabla antigua,
-- conserva su id y, por lo tanto, también su historial de reportes.
create or replace function public.sincronizar_usuario_auth()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    nombre_nuevo text;
begin
    nombre_nuevo := coalesce(
        nullif(new.raw_user_meta_data ->> 'nombre', ''),
        split_part(new.email, '@', 1)
    );

    update public.usuarios
       set auth_id = new.id,
           nombre = coalesce(nullif(nombre, ''), nombre_nuevo),
           correo = lower(new.email),
           password = null,
           activo = true
     where lower(correo) = lower(new.email)
       and (auth_id is null or auth_id = new.id);

    if not found then
        insert into public.usuarios (
            auth_id, nombre, correo, password, rol, activo
        ) values (
            new.id, nombre_nuevo, lower(new.email), null, 'ciudadano', true
        );
    end if;

    return new;
end;
$$;

drop trigger if exists al_crear_usuario_auth on auth.users;
create trigger al_crear_usuario_auth
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function public.sincronizar_usuario_auth();

-- Enlaza cuentas de Auth que ya existan antes de ejecutar este archivo.
update public.usuarios u
   set auth_id = a.id,
       password = null
  from auth.users a
 where lower(u.correo) = lower(a.email)
   and u.auth_id is null;

insert into public.usuarios (auth_id, nombre, correo, password, rol, activo)
select
    a.id,
    coalesce(nullif(a.raw_user_meta_data ->> 'nombre', ''), split_part(a.email, '@', 1)),
    lower(a.email),
    null,
    'ciudadano',
    true
from auth.users a
where not exists (
    select 1 from public.usuarios u where u.auth_id = a.id
);

-- 2) REPORTES: GPS, HISTORIAL Y MODERACIÓN SIN BORRADO FÍSICO
alter table public.reportes
    add column if not exists categoria text,
    add column if not exists ubicacion_detalle text,
    add column if not exists latitud double precision,
    add column if not exists longitud double precision,
    add column if not exists precision_ubicacion double precision,
    add column if not exists activo boolean not null default true,
    add column if not exists moderado_por uuid references auth.users(id),
    add column if not exists fecha_moderacion timestamptz;

update public.reportes set activo = true where activo is null;

-- Registra automáticamente cuándo se modera/restaura un reporte.
create or replace function public.registrar_fecha_moderacion()
returns trigger
language plpgsql
as $$
begin
    if old.activo is distinct from new.activo then
        new.fecha_moderacion := now();
    end if;
    return new;
end;
$$;

drop trigger if exists antes_de_moderar_reporte on public.reportes;
create trigger antes_de_moderar_reporte
before update of activo on public.reportes
for each row execute function public.registrar_fecha_moderacion();

-- 3) CONFIRMACIONES ÚNICAS (UN USUARIO, UNA CONFIRMACIÓN)
create table if not exists public.confirmaciones (
    id bigint generated by default as identity primary key,
    reporte_id bigint not null references public.reportes(id) on delete cascade,
    usuario_id bigint not null references public.usuarios(id) on delete cascade,
    fecha timestamptz not null default now(),
    constraint confirmacion_unica unique (reporte_id, usuario_id)
);

create or replace function public.validar_confirmacion()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if exists (
        select 1
          from public.reportes r
         where r.id = new.reporte_id
           and r.usuario_id = new.usuario_id
    ) then
        raise exception 'El autor no puede confirmar su propio reporte';
    end if;

    if not exists (
        select 1
          from public.reportes r
         where r.id = new.reporte_id
           and r.activo = true
    ) then
        raise exception 'Solo se pueden confirmar reportes visibles';
    end if;

    return new;
end;
$$;

drop trigger if exists antes_de_confirmar_reporte on public.confirmaciones;
create trigger antes_de_confirmar_reporte
before insert on public.confirmaciones
for each row execute function public.validar_confirmacion();

create or replace function public.actualizar_total_confirmaciones()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if tg_op = 'INSERT' then
        update public.reportes
           set me_sirve = coalesce(me_sirve, 0) + 1
         where id = new.reporte_id;
        return new;
    elsif tg_op = 'DELETE' then
        update public.reportes
           set me_sirve = greatest(coalesce(me_sirve, 0) - 1, 0)
         where id = old.reporte_id;
        return old;
    end if;
    return null;
end;
$$;

drop trigger if exists despues_de_confirmar_reporte on public.confirmaciones;
create trigger despues_de_confirmar_reporte
after insert or delete on public.confirmaciones
for each row execute function public.actualizar_total_confirmaciones();

-- 4) FUNCIONES AUXILIARES PARA POLÍTICAS RLS
create or replace function public.mi_usuario_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
    select id
      from public.usuarios
     where auth_id = auth.uid()
       and activo = true
     limit 1;
$$;

create or replace function public.mi_rol()
returns text
language sql
stable
security definer
set search_path = public
as $$
    select rol
      from public.usuarios
     where auth_id = auth.uid()
       and activo = true
     limit 1;
$$;

grant execute on function public.mi_usuario_id() to authenticated;
grant execute on function public.mi_rol() to authenticated;

-- 5) LIMPIEZA DE POLÍTICAS ANTIGUAS Y ROW LEVEL SECURITY
-- El proyecto anterior tenía políticas muy permisivas (USING/WITH CHECK true).
-- Las quitamos para que no anulen las políticas seguras definidas más abajo.
do $$
declare
    politica record;
begin
    for politica in
        select schemaname, tablename, policyname
          from pg_policies
         where schemaname = 'public'
           and tablename in ('usuarios', 'reportes', 'confirmaciones')
    loop
        execute format(
            'drop policy if exists %I on %I.%I',
            politica.policyname,
            politica.schemaname,
            politica.tablename
        );
    end loop;
end;
$$;

-- Quita únicamente las políticas antiguas asociadas al bucket de WaraWave.
do $$
declare
    politica record;
begin
    for politica in
        select policyname
          from pg_policies
         where schemaname = 'storage'
           and tablename = 'objects'
           and (
                policyname ilike '%reportes imagenes%'
                or coalesce(qual, '') ilike '%reportes-imagenes%'
                or coalesce(with_check, '') ilike '%reportes-imagenes%'
           )
    loop
        execute format(
            'drop policy if exists %I on storage.objects',
            politica.policyname
        );
    end loop;
end;
$$;

-- Revoca permisos antiguos antes de conceder solo los necesarios.
revoke all on public.usuarios from anon, authenticated;
revoke all on public.reportes from anon, authenticated;
revoke all on public.confirmaciones from anon, authenticated;

-- 6) ROW LEVEL SECURITY
alter table public.usuarios enable row level security;
alter table public.reportes enable row level security;
alter table public.confirmaciones enable row level security;

revoke all on public.usuarios from anon;
revoke all on public.reportes from anon;
revoke all on public.confirmaciones from anon;

grant select, update on public.usuarios to authenticated;
grant select, insert, update, delete on public.reportes to authenticated;
grant select, insert, delete on public.confirmaciones to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- USUARIOS
drop policy if exists usuarios_leer_perfil_o_admin on public.usuarios;
create policy usuarios_leer_perfil_o_admin
on public.usuarios for select
to authenticated
using (
    auth_id = auth.uid()
    or public.mi_rol() = 'administrador'
);

drop policy if exists usuarios_actualizar_admin on public.usuarios;
create policy usuarios_actualizar_admin
on public.usuarios for update
to authenticated
using (public.mi_rol() = 'administrador')
with check (rol in ('ciudadano', 'administrador', 'autoridad'));

-- REPORTES
drop policy if exists reportes_leer_permitidos on public.reportes;
create policy reportes_leer_permitidos
on public.reportes for select
to authenticated
using (
    activo = true
    or usuario_id = public.mi_usuario_id()
    or public.mi_rol() in ('administrador', 'autoridad')
);

drop policy if exists reportes_crear_propios on public.reportes;
create policy reportes_crear_propios
on public.reportes for insert
to authenticated
with check (
    usuario_id = public.mi_usuario_id()
    and activo = true
);

drop policy if exists reportes_moderar_admin on public.reportes;
create policy reportes_moderar_admin
on public.reportes for update
to authenticated
using (public.mi_rol() = 'administrador')
with check (public.mi_rol() = 'administrador');

drop policy if exists reportes_eliminar_admin on public.reportes;
create policy reportes_eliminar_admin
on public.reportes for delete
to authenticated
using (public.mi_rol() = 'administrador');

-- CONFIRMACIONES
drop policy if exists confirmaciones_leer on public.confirmaciones;
create policy confirmaciones_leer
on public.confirmaciones for select
to authenticated
using (true);

drop policy if exists confirmaciones_crear_propias on public.confirmaciones;
create policy confirmaciones_crear_propias
on public.confirmaciones for insert
to authenticated
with check (usuario_id = public.mi_usuario_id());

drop policy if exists confirmaciones_quitar_propias on public.confirmaciones;
create policy confirmaciones_quitar_propias
on public.confirmaciones for delete
to authenticated
using (usuario_id = public.mi_usuario_id());

-- 7) STORAGE PARA FOTOS Y VIDEOS
insert into storage.buckets (id, name, public, file_size_limit)
values ('reportes-imagenes', 'reportes-imagenes', true, 20971520)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit;

-- Cada usuario solo puede subir archivos a la carpeta que lleva su id interno.
drop policy if exists evidencias_subir_carpeta_propia on storage.objects;
create policy evidencias_subir_carpeta_propia
on storage.objects for insert
to authenticated
with check (
    bucket_id = 'reportes-imagenes'
    and (storage.foldername(name))[1] = public.mi_usuario_id()::text
);

-- Las evidencias son públicas porque forman parte del tablón ciudadano.
drop policy if exists evidencias_lectura_publica on storage.objects;
create policy evidencias_lectura_publica
on storage.objects for select
to public
using (bucket_id = 'reportes-imagenes');

-- El administrador puede eliminar archivos si posteriormente implementa
-- eliminación definitiva desde la aplicación.
drop policy if exists evidencias_eliminar_admin on storage.objects;
create policy evidencias_eliminar_admin
on storage.objects for delete
to authenticated
using (
    bucket_id = 'reportes-imagenes'
    and public.mi_rol() = 'administrador'
);

